import * as XLSX from 'xlsx';

interface Winery {
  name: string;
  address: string;
  city: string;
  state: string;
  zipCode: string;
  phone: string;
  website: string;
  reservationUrl: string;
  region: string;
  wineVarietals?: string;
  hoursOfOperation?: string;
  daysOpen?: string;
  visitType?: string;
  photoUrl?: string;
  latitude?: string;
  longitude?: string;
  notes?: string;
}

const wineries: Winery[] = [
  // A
  {
    name: 'Abeja',
    address: '2014 Mill Creek Road',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 526-7400',
    website: 'https://www.abeja.net',
    reservationUrl: 'https://www.abeja.net/tastings.php',
    region: 'Walla Walla Valley',
    wineVarietals: 'Cabernet Sauvignon, Merlot, Syrah, Chardonnay',
    visitType: 'By Appointment',
    photoUrl: 'https://www.abeja.net/images/Abeja-Snow-Vineyard.jpg',
  },
  {
    name: 'Adamant Cellars',
    address: '525 East Cessna Avenue',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 529-4161',
    website: 'https://adamantcellars.com',
    reservationUrl: 'https://square.site/book/8AK8PD1TKKYX8/adamant-cellars-walla-walla-wa',
    region: 'Walla Walla Valley',
  },
  {
    name: 'ALUVÉ',
    address: '100 Aluvé Lane',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 520-6251',
    website: 'https://www.aluvewine.com',
    reservationUrl: 'https://www.aluvewine.com/visit',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Amavi Cellars',
    address: '3796 Peppers Bridge Road',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 525-3541',
    website: 'https://www.amavicellars.com',
    reservationUrl: 'https://www.amavicellars.com/tours-tastings',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Arenness Cellars',
    address: '602 Piper Ave',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 540-5175',
    website: 'https://arennesscellars.com',
    reservationUrl: 'https://arennesscellars.com/pages/visit-us',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Armstrong Family Winery',
    address: '9 N 2nd Ave',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 524-8494',
    website: 'https://www.armstrongwinery.com',
    reservationUrl: 'https://www.armstrongwinery.com/visit/reservations',
    region: 'Walla Walla Valley - Downtown',
  },
  {
    name: 'August Forest',
    address: '594 Piper Ave',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 593-8652',
    website: 'https://augustforest.com',
    reservationUrl: 'https://augustforest.com/',
    region: 'Walla Walla Valley',
  },
  // B
  {
    name: 'Balboa Winery',
    address: '4169 Peppers Bridge Road',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 529-0461',
    website: 'https://balboawinery.com',
    reservationUrl: 'https://www.exploretock.com/balboawinery',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Bartholomew Winery',
    address: '12 N 2nd Ave',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(206) 395-8460',
    website: 'https://www.bartholomewwinery.com',
    reservationUrl: 'https://www.bartholomewwinery.com/walla-walla.html',
    region: 'Walla Walla Valley - Downtown',
  },
  {
    name: 'Beekeeper by Abeja',
    address: '6 West Rose Street, #101',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 520-8541',
    website: 'https://www.abeja.net',
    reservationUrl: 'https://www.exploretock.com/abeja-/',
    region: 'Walla Walla Valley - Downtown',
  },
  {
    name: 'Bledsoe Family Winery',
    address: '229 East Main Street',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 792-3510',
    website: 'https://bledsoefamilywinery.com',
    reservationUrl: 'https://www.exploretock.com/bledsoefamilywinery',
    region: 'Walla Walla Valley - Downtown',
  },
  {
    name: 'Bledsoe | McDaniels',
    address: '178 Vineyard Lane',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 392-7050',
    website: 'https://www.bledsoemcdaniels.com',
    reservationUrl: 'https://www.bledsoemcdaniels.com/Visit',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Browne Family Vineyards',
    address: '31 East Main Street',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 522-1261',
    website: 'https://brownefamilyvineyards.com',
    reservationUrl: 'https://brownefamilyvineyards.com/visit/walla-walla/',
    region: 'Walla Walla Valley - Downtown',
  },
  // C
  {
    name: 'Capital Call Vintners',
    address: '11 N Second Avenue',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 876-2056',
    website: 'https://capitalcallvintners.com',
    reservationUrl: 'https://capitalcallvintners.com/walla-walla-tasting-room/',
    region: 'Walla Walla Valley - Downtown',
  },
  {
    name: 'Caprio Cellars',
    address: '1603 Whiteley Road',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 412-3054',
    website: 'https://www.capriocellars.com',
    reservationUrl: 'https://www.capriocellars.com/',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Cayuse Vineyards',
    address: '53863 Highway 332',
    city: 'Milton-Freewater',
    state: 'OR',
    zipCode: '97862',
    phone: '(509) 526-0686',
    website: 'https://cayusevineyards.com',
    reservationUrl: '',
    region: 'The Rocks District of Milton-Freewater',
    notes: 'Also has location at 17 East Main Street, Walla Walla, WA 99362',
  },
  {
    name: 'Cimento',
    address: '',
    city: 'Milton-Freewater',
    state: 'OR',
    zipCode: '97862',
    phone: '(541) 224-6608',
    website: 'https://cimentowines.com',
    reservationUrl: '',
    region: 'The Rocks District of Milton-Freewater',
  },
  {
    name: 'College Cellars of Walla Walla',
    address: '3020 East Isaacs Avenue',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 524-5170',
    website: 'https://collegecellars.com',
    reservationUrl: 'https://app.acuityscheduling.com/schedule.php?owner=20165232',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Corliss',
    address: '511 North Second Avenue',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 526-4400',
    website: 'https://corlissestate.com',
    reservationUrl: '',
    region: 'Walla Walla Valley - Downtown',
  },
  // D
  {
    name: 'DAMA Wines',
    address: '123 East Main Street',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 525-2299',
    website: 'https://www.damawines.com',
    reservationUrl: 'https://www.damawines.com/reservations/',
    region: 'Walla Walla Valley - Downtown',
  },
  {
    name: 'Delmas',
    address: '',
    city: 'Milton-Freewater',
    state: 'OR',
    zipCode: '97862',
    phone: '(541) 419-1718',
    website: 'https://delmaswines.com',
    reservationUrl: '',
    region: 'The Rocks District of Milton-Freewater',
  },
  {
    name: 'Deux Soldats Estate Vineyard & Winery',
    address: '1180 Whiteley Rd',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 956-9939',
    website: 'https://deuxsoldats.com',
    reservationUrl: 'https://deuxsoldats.com/reservation/',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Dossier Wine Collective',
    address: '8 West Main Street',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 590-1399',
    website: 'https://dossierwine.com',
    reservationUrl: 'https://dossierwine.com/walla-walla-tr',
    region: 'Walla Walla Valley - Downtown',
  },
  {
    name: 'Doubleback',
    address: '3853 Powerline Road',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 525-3334',
    website: 'https://www.doubleback.com',
    reservationUrl: '',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Ducleaux Cellars',
    address: '54211 Turbyne Road',
    city: 'Milton-Freewater',
    state: 'OR',
    zipCode: '97862',
    phone: '(206) 227-7256',
    website: 'https://www.ducleauxcellars.com',
    reservationUrl: 'https://www.ducleauxcellars.com/bookings-checkout/wine-tasting-appointment/book',
    region: 'The Rocks District of Milton-Freewater',
  },
  {
    name: 'Dunham Cellars',
    address: '150 East Boeing Avenue',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 529-4685',
    website: 'https://www.dunhamcellars.com',
    reservationUrl: 'https://www.dunhamcellars.com/Contact-Us/Visit-Us',
    region: 'Walla Walla Valley - Airport',
  },
  {
    name: 'Dusted Valley',
    address: '1248 Old Milton Highway',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 525-1337',
    website: 'https://www.dustedvalley.com',
    reservationUrl: 'https://www.dustedvalley.com/visitus/',
    region: 'Walla Walla Valley',
  },
  // E
  {
    name: 'Echolands Winery',
    address: '3281 Mill Creek Road',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 676-2109',
    website: 'https://www.echolandswinery.com',
    reservationUrl: 'https://www.echolandswinery.com/visit',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Eleganté Cellars',
    address: '839 C Street',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 525-9129',
    website: '',
    reservationUrl: '',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Eternal Wines',
    address: '85514 OR-11',
    city: 'Milton-Freewater',
    state: 'OR',
    zipCode: '97862',
    phone: '(509) 240-6258',
    website: 'https://eternalwines.com',
    reservationUrl: '',
    region: 'The Rocks District of Milton-Freewater',
  },
  {
    name: 'EVEREN Wines',
    address: '1823 Old Milton Hwy',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(971) 219-7170',
    website: 'https://www.everenwines.com',
    reservationUrl: 'https://www.everenwines.com/',
    region: 'Walla Walla Valley',
  },
  // F
  {
    name: 'FIGGINS & Toil Oregon',
    address: '3917 Mill Creek Road',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 522-7098',
    website: 'http://www.figginswine.com',
    reservationUrl: 'http://www.figginswine.com/experience',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Five Star Cellars',
    address: '840 C Street',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 527-8400',
    website: 'https://fivestarcellars.com',
    reservationUrl: '',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Floating Balance Cellars',
    address: '2100 Stateline Road',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 520-3869',
    website: 'https://www.floatingbalance.com',
    reservationUrl: 'https://www.floatingbalance.com/reservations/',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Foolhardy Vintners',
    address: '134 W. Poplar Street',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(917) 533-6275',
    website: 'https://www.foolhardyvintners.com',
    reservationUrl: 'https://www.foolhardyvintners.com/tastingroom',
    region: 'Walla Walla Valley - Downtown',
  },
  {
    name: 'Force Majeure',
    address: '52274 Pleasant View Road',
    city: 'Milton-Freewater',
    state: 'OR',
    zipCode: '97862',
    phone: '(541) 833-3051',
    website: 'https://forcemajeurevineyards.com',
    reservationUrl: 'https://forcemajeurevineyards.com/visit/',
    region: 'The Rocks District of Milton-Freewater',
  },
  {
    name: 'Forgeron Cellars',
    address: '33 West Birch Street',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 522-9463',
    website: 'https://forgeroncellars.com',
    reservationUrl: 'https://forgeroncellars.orderport.net/reservations',
    region: 'Walla Walla Valley - Downtown',
  },
  {
    name: 'Foundry Vineyards',
    address: '1111 Abadie Street',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 529-0736',
    website: 'https://www.foundryvineyards.com',
    reservationUrl: 'https://www.foundryvineyards.com/book-online',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Freewater Winery',
    address: '525 N Elizabeth Street',
    city: 'Milton-Freewater',
    state: 'OR',
    zipCode: '97862',
    phone: '(509) 499-7368',
    website: 'https://www.freewaterco.com',
    reservationUrl: 'https://www.freewaterco.com/Tasting',
    region: 'The Rocks District of Milton-Freewater',
  },
  // G
  {
    name: 'Garrison Creek Cellars',
    address: '4153 Hood Road',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 525-7377',
    website: 'https://www.garrisoncreekcellars.com',
    reservationUrl: '',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Gifford Hirlinger',
    address: '1450 Stateline Road',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 301-9229',
    website: 'https://giffordhirlinger.com',
    reservationUrl: '',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Gramercy Cellars',
    address: '635 North 13th Avenue',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 876-2427',
    website: 'https://gramercycellars.com',
    reservationUrl: 'https://gramercycellars.com/visit/',
    region: 'Walla Walla Valley',
    wineVarietals: 'Cabernet Sauvignon, Syrah, Pinot Noir, Cabernet Franc, Mourvèdre, Rosé, Picpoul',
    visitType: 'By Appointment',
    photoUrl: 'https://gramercycellars.com/wp-content/uploads/2025/03/Tasting-Room-Mast-1500x900.jpg',
    notes: 'Specializes in Rhône and Bordeaux blends',
  },
  {
    name: 'Grosgrain Vineyards',
    address: '2158 Half Acre Lane',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 876-4045',
    website: 'https://grosgrainvineyards.com',
    reservationUrl: 'https://grosgrainvineyards.com/visit/',
    region: 'Walla Walla Valley',
  },
  // H
  {
    name: 'Horsepower Vineyards',
    address: '',
    city: 'Milton-Freewater',
    state: 'OR',
    zipCode: '97862',
    phone: '(509) 526-1515',
    website: 'https://horsepowervineyards.com',
    reservationUrl: '',
    region: 'The Rocks District of Milton-Freewater',
  },
  {
    name: 'House of Smith',
    address: '35 S Spokane Street',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 526-5230',
    website: 'https://houseofsmith.com',
    reservationUrl: 'https://www.exploretock.com/house-of-smith-tasting-room-walla-walla',
    region: 'Walla Walla Valley - Downtown',
  },
  // I
  {
    name: 'itä wines',
    address: '600 Piper Avenue',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 593-9055',
    website: 'https://itawinery.com',
    reservationUrl: 'https://itawinery.com/reservation/',
    region: 'Walla Walla Valley',
  },
  // J
  {
    name: 'Jett Wines',
    address: '2900 Melrose Street',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 202-4300',
    website: 'https://www.jettwines.com',
    reservationUrl: 'https://www.jettwines.com/visit.html',
    region: 'Walla Walla Valley',
  },
  // K
  {
    name: 'K Vintners',
    address: '820 Mill Creek Road',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 526-5230',
    website: 'https://houseofsmith.com/brands/kvintners-wines/',
    reservationUrl: 'https://houseofsmith.com/brands/kvintners-wines/',
    region: 'Walla Walla Valley',
  },
  {
    name: 'KINHAVEN Winery',
    address: '1050 Merlot Drive',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 525-1226',
    website: 'https://kinhavenwinery.com',
    reservationUrl: 'https://kinhavenwinery.as.me/schedule.php',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Kontos Cellars',
    address: '10 North Second Avenue',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 204-2141',
    website: 'https://kontoscellars.com',
    reservationUrl: 'https://www.exploretock.com/kontoscellars',
    region: 'Walla Walla Valley - Downtown',
  },
  // L
  {
    name: 'Lagana Cellars',
    address: '16 North Second Avenue',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 876-0001',
    website: 'https://laganacellars.com',
    reservationUrl: 'https://laganacellars.com/reservation/',
    region: 'Walla Walla Valley - Downtown',
  },
  {
    name: 'Leonetti Cellar',
    address: '',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 525-1428',
    website: 'https://leonetticellar.com',
    reservationUrl: '',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Long Shadows Vintners',
    address: '1604 Frenchtown Road',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 526-0905',
    website: 'https://longshadows.com',
    reservationUrl: '',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Los Rocosos Vineyards',
    address: '84038 Eastside Road',
    city: 'Milton-Freewater',
    state: 'OR',
    zipCode: '97862',
    phone: '(541) 306-1290',
    website: 'https://losrocososvineyards.com',
    reservationUrl: '',
    region: 'The Rocks District of Milton-Freewater',
  },
  {
    name: "L'Ecole № 41",
    address: '41 Lowden School Road',
    city: 'Lowden',
    state: 'WA',
    zipCode: '99360',
    phone: '(509) 525-0940',
    website: 'https://www.lecole.com',
    reservationUrl: 'https://www.lecole.com/visit-us/',
    region: 'Walla Walla Valley',
  },
  {
    name: "L'Ecole № 41 Heritage Wine Bar",
    address: '6 West Rose St, Ste 103',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 525-0940',
    website: 'https://www.lecole.com',
    reservationUrl: '',
    region: 'Walla Walla Valley - Downtown',
  },
  // M
  {
    name: 'Maison Bleue Winery',
    address: '20 North Second Avenue',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 525-9084',
    website: 'https://mbwinery.com',
    reservationUrl: '',
    region: 'Walla Walla Valley - Downtown',
  },
  {
    name: 'Mercer Wine Estates',
    address: '18 E Main Street',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 204-5450',
    website: 'https://mercerwine.com',
    reservationUrl: 'https://www.exploretock.com/mercerwine',
    region: 'Walla Walla Valley - Downtown',
  },
  {
    name: 'Mongata Estate Winery',
    address: '81768 South Fork Walla Walla River Rd',
    city: 'Milton-Freewater',
    state: 'OR',
    zipCode: '97862',
    phone: '(541) 861-9485',
    website: 'https://mongatawinery.com',
    reservationUrl: 'https://mongatawinery.com/visit/',
    region: 'The Rocks District of Milton-Freewater',
  },
  {
    name: 'Moonbase Cellars',
    address: '7 N 2nd Avenue',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 876-4025',
    website: 'https://moonbase.wine',
    reservationUrl: 'https://moonbase.wine/products/booking-page',
    region: 'Walla Walla Valley - Downtown',
  },
  // N
  {
    name: 'No Girls Wines',
    address: '',
    city: 'Milton-Freewater',
    state: 'OR',
    zipCode: '97862',
    phone: '(509) 525-9787',
    website: 'https://nogirlswines.com',
    reservationUrl: '',
    region: 'The Rocks District of Milton-Freewater',
  },
  {
    name: 'Northstar',
    address: '1736 J B George Road',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 525-6100',
    website: 'https://www.northstarwinery.com',
    reservationUrl: 'https://www.northstarwinery.com/visiting/tasting-room',
    region: 'Walla Walla Valley',
  },
  // P
  {
    name: 'Pambrun Wines',
    address: '20 North Second Avenue',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 525-9084',
    website: 'https://mbwinery.com',
    reservationUrl: '',
    region: 'Walla Walla Valley - Downtown',
  },
  {
    name: 'Patterson Cellars',
    address: '1564 Whiteley Road',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 524-8915',
    website: 'https://pattersoncellarswines.com',
    reservationUrl: 'https://www.cellarpass.com/profile/patterson-cellars-walla-walla',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Pepper Bridge Winery',
    address: '1704 J B George Road',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 525-6502',
    website: 'https://www.pepperbridge.com',
    reservationUrl: 'https://www.pepperbridge.com/visit/walla-walla',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Proper Wines & House of Bones',
    address: '31 East Main Street, #216',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 301-9074',
    website: 'https://www.properwines.com',
    reservationUrl: 'https://www.properwines.com/Visit',
    region: 'Walla Walla Valley - Downtown',
  },
  {
    name: 'Pursued by Bear',
    address: '43 South Palouse Street',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 524-8175',
    website: 'https://pursuedbybear.com',
    reservationUrl: 'https://www.exploretock.com/pursued-by-bear-walla-walla/',
    region: 'Walla Walla Valley - Downtown',
  },
  // R
  {
    name: 'REALI',
    address: '800 Vintners Vista Lane',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(901) 581-0995',
    website: 'https://realifamilyvineyard.com',
    reservationUrl: 'https://realifamilyvineyard.com/',
    region: 'Walla Walla Valley',
  },
  {
    name: 'REININGER Winery & Helix Wines',
    address: '5858 Old Highway 12',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 522-1994',
    website: 'https://reiningerwinery.com',
    reservationUrl: '',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Rôtie Cellars',
    address: '84328 Trumbull Lane',
    city: 'Milton-Freewater',
    state: 'OR',
    zipCode: '97862',
    phone: '(509) 301-9074',
    website: 'https://www.rotiecellars.com',
    reservationUrl: 'https://www.rotiecellars.com/Taste/Rotie-Rocks-Estate',
    region: 'The Rocks District of Milton-Freewater',
  },
  // S
  {
    name: 'Sagemoor',
    address: '1648 Stateline Rd',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 540-3285',
    website: 'https://sagemoorestates.com',
    reservationUrl: 'https://sagemoorestates.com/requests',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Saviah Cellars',
    address: '1979 J B George Road',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 522-2181',
    website: 'https://www.saviahcellars.com',
    reservationUrl: 'https://www.saviahcellars.com/visit/tasting-tours/',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Seven Hills Winery',
    address: '212 North Third Avenue',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 529-7198',
    website: 'https://www.sevenhillswinery.com',
    reservationUrl: 'https://www.sevenhillswinery.com/visit/',
    region: 'Walla Walla Valley - Downtown',
    wineVarietals: 'Merlot, Cabernet Sauvignon',
    visitType: 'Private Seated Tastings',
    photoUrl: 'https://sevenhillswinery.com/wp-content/uploads/2023/05/Seven-Hills-Winery-Pentad-Tasting-Room.png',
    notes: 'Downtown Walla Walla\'s only historic working winemaking facility, established 1988',
  },
  {
    name: 'Sleight of Hand Cellars',
    address: '1959 J B George Road',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 525-3661',
    website: 'https://www.sofhcellars.com',
    reservationUrl: 'https://www.sofhcellars.com/contact',
    region: 'Walla Walla Valley',
  },
  {
    name: 'SMAK Wines',
    address: '594 Piper Avenue',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 629-9643',
    website: 'https://www.smakwines.com',
    reservationUrl: 'https://www.smakwines.com/visit',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Smoky Rose Cellars',
    address: '2428 Heritage Road',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 508-1022',
    website: 'https://smokyrosecellars.com',
    reservationUrl: '',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Spring Valley Vineyard',
    address: '2 East Rose Street',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 525-1506',
    website: 'https://www.springvalleyvineyard.com',
    reservationUrl: 'https://www.springvalleyvineyard.com/winery/tasting_room',
    region: 'Walla Walla Valley - Downtown',
  },
  {
    name: 'SYZYGY',
    address: '405 East Boeing Avenue',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 522-0484',
    website: 'https://syzygywine.com',
    reservationUrl: 'https://squareup.com/appointments/book/3NQK4SXGY5A0X',
    region: 'Walla Walla Valley - Airport',
  },
  // T
  {
    name: 'Tempus Cellars',
    address: '760 C Street',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 270-0298',
    website: 'https://tempuscellars.com',
    reservationUrl: '',
    region: 'Walla Walla Valley',
  },
  {
    name: 'The Walls Vineyards',
    address: '1015 West Pine Street',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 876-0200',
    website: 'http://www.thewallswines.com',
    reservationUrl: 'http://www.thewallswines.com/visit-us/',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Time & Direction',
    address: '4 North Spokane Street',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 524-8200',
    website: 'https://www.timeanddirectionwines.com',
    reservationUrl: 'https://www.timeanddirectionwines.com/reservation/',
    region: 'Walla Walla Valley - Downtown',
  },
  {
    name: 'Tranche',
    address: '705 Berney Drive',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 526-3500',
    website: 'https://www.tranche.wine',
    reservationUrl: 'https://www.tranche.wine/visit',
    region: 'Walla Walla Valley',
  },
  // V
  {
    name: 'Va Piano Vineyards',
    address: '1793 J B George Road',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 529-0900',
    website: 'https://vapianovineyards.com',
    reservationUrl: 'https://vapianovineyards.orderport.net/reservations',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Valdemar Estates',
    address: '3808 Rolling Hills Lane',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 956-4926',
    website: 'https://valdemarusa.com',
    reservationUrl: 'https://www.exploretock.com/valdemarestateswallawalla',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Vital Wines',
    address: '17 North Second Avenue',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 540-2323',
    website: 'https://vitalwines.com',
    reservationUrl: '',
    region: 'Walla Walla Valley - Downtown',
  },
  // W
  {
    name: 'Walla Walla Vintners',
    address: '225 Vineyard Lane',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 525-4724',
    website: 'https://wallawallavintners.com',
    reservationUrl: 'https://wallawallavintners.com/reservations/',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Waterbrook Winery & Kitchen',
    address: '10518 US-12',
    city: 'Walla Walla',
    state: 'WA',
    zipCode: '99362',
    phone: '(509) 522-1262',
    website: 'https://waterbrook.com',
    reservationUrl: 'https://waterbrook.com/tasting-room',
    region: 'Walla Walla Valley',
  },
  {
    name: 'Watermill Winery',
    address: '235 East Broadway Avenue',
    city: 'Milton-Freewater',
    state: 'OR',
    zipCode: '97862',
    phone: '(541) 938-5575',
    website: 'https://www.watermillwinery.com',
    reservationUrl: 'https://www.watermillwinery.com/#tastingRooms',
    region: 'The Rocks District of Milton-Freewater',
  },
  {
    name: 'Windrow Estate Winery',
    address: '52015 Seven Hills Road',
    city: 'Milton-Freewater',
    state: 'OR',
    zipCode: '97862',
    phone: '(509) 593-0162',
    website: 'https://www.windrowestate.com',
    reservationUrl: 'https://www.windrowestate.com/book-a-tasting',
    region: 'The Rocks District of Milton-Freewater',
  },
  {
    name: 'Woodward Canyon',
    address: '11920 Old Highway 12',
    city: 'Lowden',
    state: 'WA',
    zipCode: '99360',
    phone: '(509) 525-4129',
    website: 'https://www.woodwardcanyon.com',
    reservationUrl: '',
    region: 'Walla Walla Valley',
  },
  // Z
  {
    name: 'Zerba Cellars',
    address: '85530 Highway 11',
    city: 'Milton-Freewater',
    state: 'OR',
    zipCode: '97862',
    phone: '(541) 938-9463',
    website: 'https://zerbacellars.com',
    reservationUrl: '',
    region: 'The Rocks District of Milton-Freewater',
  },
];

// Create workbook and worksheet
const wb = XLSX.utils.book_new();

// Convert data to worksheet format
const wsData = [
  // Header row
  [
    'Winery Name',
    'Address',
    'City',
    'State',
    'Zip Code',
    'Phone',
    'Website',
    'Reservation URL',
    'Region/District',
    'Wine Varietals',
    'Hours of Operation',
    'Days Open',
    'Visit Type',
    'Photo URL',
    'Latitude',
    'Longitude',
    'Notes',
  ],
  // Data rows
  ...wineries.map((winery) => [
    winery.name,
    winery.address,
    winery.city,
    winery.state,
    winery.zipCode,
    winery.phone,
    winery.website,
    winery.reservationUrl,
    winery.region,
    winery.wineVarietals || 'Cabernet Sauvignon, Merlot, Syrah (typical Walla Walla)',
    winery.hoursOfOperation || 'Contact winery for hours',
    winery.daysOpen || 'Varies - check website',
    winery.visitType || (winery.reservationUrl ? 'By Appointment/Reservation' : 'Contact for details'),
    winery.photoUrl || '',
    winery.latitude || '',
    winery.longitude || '',
    winery.notes || '',
  ]),
];

const ws = XLSX.utils.aoa_to_sheet(wsData);

// Set column widths
ws['!cols'] = [
  { wch: 35 }, // Winery Name
  { wch: 30 }, // Address
  { wch: 20 }, // City
  { wch: 8 }, // State
  { wch: 10 }, // Zip Code
  { wch: 18 }, // Phone
  { wch: 40 }, // Website
  { wch: 50 }, // Reservation URL
  { wch: 35 }, // Region/District
  { wch: 45 }, // Wine Varietals
  { wch: 30 }, // Hours of Operation
  { wch: 25 }, // Days Open
  { wch: 25 }, // Visit Type
  { wch: 50 }, // Photo URL
  { wch: 12 }, // Latitude
  { wch: 12 }, // Longitude
  { wch: 50 }, // Notes
];

// Add worksheet to workbook
XLSX.utils.book_append_sheet(wb, ws, 'Walla Walla Wineries');

// Write to file
const fileName = 'walla-walla-wineries.xlsx';
XLSX.writeFile(wb, fileName);

console.log(`\n✓ Successfully created ${fileName}`);
console.log(`  Total wineries: ${wineries.length}`);
console.log(`  Regions covered:`);
console.log(`    - Walla Walla Valley (WA)`);
console.log(`    - The Rocks District of Milton-Freewater (OR)`);
console.log(`\nData fields included:`);
console.log(`  • Contact: Name, Address, Phone, Website`);
console.log(`  • Reservations: Booking URLs, Visit Type`);
console.log(`  • Wine Info: Varietals (Cab, Merlot, Syrah, etc.)`);
console.log(`  • Operations: Hours, Days Open`);
console.log(`  • Media: Photo URLs`);
console.log(`  • Location: Lat/Long coordinates (placeholders)`);
console.log(`\nNext steps:`);
console.log(`  1. Review and verify the data`);
console.log(`  2. Visit individual winery websites to populate specific hours/photos`);
console.log(`  3. Add latitude/longitude coordinates using geocoding`);
console.log(`  4. Import into your database`);
